name: sqflite_support
description: sqflite support tools
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.7.1 <3.0.0'

dependencies:
  process_run: '>=0.10.10+2'
  path:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
