name: sqflite_github_test
description: Testing from git
publish_to: none
# version: 1.0.0
# homepage: https://www.example.com
# author: alex <email@example.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  sqflite:
  sqflite_test:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: dart2
      path: sqflite_test
    version: '>=0.1.0'
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.0.0
  flutter_test:
    sdk: flutter
  test:
  sqflite_ffi_test:
    git:
      url: git://github.com/tekartik/sqflite_more
      ref: dart2
      path: sqflite_ffi_test
    version: '>=0.0.1'

dependency_overrides:
  # sqflite_server:
  #  path: ../../sqflite_server
  # sqflite_test:
  #  path: ../../sqflite_test
  # sqflite_ffi_test:
  #  path: ../../sqflite_ffi_test
  sqflite_common_server:
    path: ../../sqflite_common_server
    # git:
    #   url: git://github.com/tekartik/sqflite_more.dart
    #  ref: dart2
    #  path: sqflite_common_server
    #  version: '>=0.3.1'
# Here we use sqflite from git
  sqflite:
    git:
      url: git://github.com/tekartik/sqflite
      path: sqflite
      version: '>=1.3.0'

