name: _
publish_to: none
environment:
  sdk: ^3.10.0
workspace:
  - repo_support
  - sqflite_common_porter
  - sqflite_common_server
  - sqflite_common_test_app
  - sqflite_porter
  - sqflite_server_app
  - sqflite_support
  - sqflite_test
  - sqflite_test_app
  - various/sqflite_isolate_test_app
