name: sqflite_more_repo
description: sqflite more repo (tools)
version: 0.1.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dev_dependencies:
  test: ">=1.2.0"
  dev_test: '>=0.12.0-dev.1'
  grinder: any
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.3.4'
  tekartik_travis_ci_flutter:
    git:
      url: git://github.com/tekartik/travis_ci_flutter.dart
      ref: dart2

