name: example
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  sqflite_ffi_test:
    path: ../

flutter:
  uses-material-design: true