name: sqflite_common_test_app
description: A simple command-line application.
version: 1.0.0
homepage: https://github.com/tekartik/sqflite_more/tree/master/sqflite_common_test_app
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sqflite_common: '>=2.0.0+2'
  path:

dev_dependencies:
  sqflite_common_ffi: '>=2.3.1'
  process_run:
  test:
  dev_build:
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      ref: dart3a
      path: packages/lints_flutter
    version: '>=0.1.0'
