name: sqflite_common_test_app
description: A simple command-line application.
version: 1.0.0
homepage: https://github.com/tekartik/sqflite_more/tree/master/sqflite_common_test_app
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  sqflite_common: '>=2.0.0+2'
  path: ">=1.9.0"

dev_dependencies:
  sqflite_common_ffi: ">=2.3.4"
  process_run: ">=1.2.1+1"
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      path: packages/lints_flutter
    version: '>=0.1.0'
resolution: workspace
