name: sqflite_common_porter
description: Sqflite import and export
version: 0.3.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: any
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.9.7+1'
  csv:
  sqflite_common_ffi: '>=2.3.1'
  sqflite_common:

dev_dependencies:
  test:
  process_run: '>=0.10.3'
  dev_test:
