name: sqflite_common_server
description: Sqflite server common component
version: 0.3.3
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path:
  sqflite_common: '>=1.0.0+1'
  tekartik_web_socket_io:
    git:
      url: git://github.com/tekartik/web_socket.dart
      ref: dart2
      path: web_socket_io
    version: '>=0.2.0'
  json_rpc_2:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.9.7+1'


dev_dependencies:
  sqflite_common_ffi:
  test:
  process_run: '>=0.10.7'

dependency_overrides:
  pedantic: '>=1.9.0'
