name: sqflite_common_server
description: Sqflite server common component
version: 0.3.3
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path:
  sqflite_common: '>2.5.0+2'
  tekartik_web_socket_io:
    git:
      url: https://github.com/tekartik/web_socket.dart
      ref: dart3a
      path: web_socket_io
    version: '>=0.2.0'
  json_rpc_2:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.9.7+1'


dev_dependencies:
  sqflite_common_ffi: '>=2.3.1'
  test:
  process_run: '>=0.10.7'
  dev_test:

dependency_overrides:
