name: sqflite_ffi
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: alex <alex@tekartik.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  process_run: '>=0.10.4+1'

dependency_overrides:
  pedantic: '>=1.9.0'